# Book settings
title: FinSim Documentation
author: PolicyEngine
logo: logo.png
copyright: "2024"

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: cache
  timeout: 600
  
# Define the name of the latex output file for PDF builds
latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true
  latex_documents:
    targetname: finsim.tex

# Add a bibtex file so citations can be used
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/PolicyEngine/finsim
  branch: master
  path_to_book: docs

# Add GitHub buttons to pages
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  
sphinx:
  extra_extensions:
    - sphinx.ext.napoleon
    - sphinx.ext.viewcode
    - sphinxcontrib.mermaid
  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      repository_url: https://github.com/PolicyEngine/finsim
      use_repository_button: true
      use_issues_button: true
      use_download_button: true
      home_page_in_toc: true